title: BlueLiteBlocker
description: A multi-functional browser extension for filtering & blocking Twitter Blue users.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
